spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  ssl:
    key-store: classpath:ssl-server.jks
    key-store-type: JKS
    key-password: 123456
    key-alias: server_key
  port: 8081
